/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
#include <qmessagebox.h>
/* Header for class org_swdc_qt_internal_dialogs_SMessageDialog */

#ifndef _Included_org_swdc_qt_internal_dialogs_SMessageDialog
#define _Included_org_swdc_qt_internal_dialogs_SMessageDialog
#ifdef __cplusplus
extern "C" {
#endif

class SMessageDialog : public QMessageBox {

private:
    jobject self;
public:
    SMessageDialog(jobject self);
    SMessageDialog(jobject self,QWidget*);
protected:
    void paintEvent(QPaintEvent *event);
};

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    addButton
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_addButton__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    addButton
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_addButton__JLjava_lang_String_2I
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    addButton
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_addButton__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    removeButton
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_removeButton
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    buttons
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_buttons
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    buttonRole
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_buttonRole
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setStandardButtons
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setStandardButtons
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    standardButton
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_standardButton
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    button
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_button
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    defaultButton
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_defaultButton
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setDefaultButton
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setDefaultButton__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setDefaultButton
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setDefaultButton__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    escapeButton
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_escapeButton
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setEscapeButton
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setEscapeButton__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setEscapeButton
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setEscapeButton__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    clickedButton
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_clickedButton
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    text
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_text
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    icon
 * Signature: (J)J
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_icon
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setIcon
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setIcon
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    iconPixmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_iconPixmap
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setIconPixmap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setIconPixmap
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    buttonText
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_buttonText
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setButtonText
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setButtonText
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    informativeText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_informativeText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    setInformativeText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_setInformativeText
  (JNIEnv *, jobject, jlong, jstring);
/*
 * Class:     org_swdc_qt_internal_dialogs_SMessageDialog
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SMessageDialog_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
