/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_dialogs_SDialog */

#ifndef _Included_org_swdc_qt_internal_dialogs_SDialog
#define _Included_org_swdc_qt_internal_dialogs_SDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    result
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_result
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    setVisible
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_setVisible
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    sizeHint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_sizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    minimumSizeHint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_minimumSizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    setSizeGripEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_setSizeGripEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    isSizeGripEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_isSizeGripEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    setModal
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_setModal
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    setResult
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_setResult
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    open
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_open
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    exec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_exec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    done
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_done
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    accept
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_accept
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    reject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_reject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_dialogs_SDialog
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_dialogs_SDialog_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
