/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_common_SAbstractItemModel */

#ifndef _Included_org_swdc_qt_internal_common_SAbstractItemModel
#define _Included_org_swdc_qt_internal_common_SAbstractItemModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    hasIndex
 * Signature: (JIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_hasIndex
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    index
 * Signature: (JIIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_index
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    parent
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_parent
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    sibling
 * Signature: (JIIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_sibling
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    rowCount
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_rowCount
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    columnCount
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_columnCount
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    hasChildren
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_hasChildren
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    data
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_data
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    setData
 * Signature: (JJJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_setData
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    headerData
 * Signature: (JIJI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_headerData
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    setHeaderData
 * Signature: (JIJJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_setHeaderData
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    insertRows
 * Signature: (JIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_insertRows
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    insertColumns
 * Signature: (JIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_insertColumns
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    removeRows
 * Signature: (JIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_removeRows
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    removeColumns
 * Signature: (JIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_removeColumns
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    moveRows
 * Signature: (JJIIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_moveRows
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    moveColumns
 * Signature: (JJIIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_moveColumns
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    insertRow
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_insertRow
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    insertColumn
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_insertColumn
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    removeRow
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_removeRow
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    removeColumn
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_removeColumn
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    moveRow
 * Signature: (JJIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_moveRow
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    moveColumn
 * Signature: (JJIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_moveColumn
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    fetchMore
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_fetchMore
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    canFetchMore
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_canFetchMore
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    flags
 * Signature: (JJ)I
 */
/*JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_flags
  (JNIEnv *, jobject, jlong, jlong);*/

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    sort
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_sort
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    buddy
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_buddy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    match
 * Signature: (JJIJII)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_match
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    span
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_span
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    submit
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_submit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SAbstractItemModel
 * Method:    revert
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SAbstractItemModel_revert
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
