/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_common_SLine */

#ifndef _Included_org_swdc_qt_internal_common_SLine
#define _Included_org_swdc_qt_internal_common_SLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SLine_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    p1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SLine_p1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    p2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SLine_p2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    x1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_common_SLine_x1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    y1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_common_SLine_y1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    x2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_common_SLine_x2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    y2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_common_SLine_y2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    dx
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_common_SLine_dx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    dy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_common_SLine_dy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    translate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SLine_translate__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    translate
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SLine_translate__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    translated
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SLine_translated__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    translated
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SLine_translated__JII
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    center
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_common_SLine_center
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    setP1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SLine_setP1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    setP2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SLine_setP2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    setPoints
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SLine_setPoints
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    setLine
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SLine_setLine
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     org_swdc_qt_internal_common_SLine
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_common_SLine_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
