/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_layout_SLayoutItem */

#ifndef _Included_org_swdc_qt_internal_layout_SLayoutItem
#define _Included_org_swdc_qt_internal_layout_SLayoutItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    getSizeHint
 * Signature: (J)Lorg/swdc/qt/beans/SSize;
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_getSizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    getMinimumSize
 * Signature: (J)Lorg/swdc/qt/beans/SSize;
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_getMinimumSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    getMaximumSize
 * Signature: (J)Lorg/swdc/qt/beans/SSize;
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_getMaximumSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    setGeometry
 * Signature: (JIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_setGeometry
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    getGeometry
 * Signature: (J)Lorg/swdc/qt/beans/SRect;
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_getGeometry
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    isEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_isEmpty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    hasHeightForWidth
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_hasHeightForWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    setHeightForWidth
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_setHeightForWidth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    setMinimumHeightForWidth
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_setMinimumHeightForWidth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_layout_SLayoutItem
 * Method:    doInvalidate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SLayoutItem_doInvalidate
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
