/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_layout_SHBoxLayout */

#ifndef _Included_org_swdc_qt_internal_layout_SHBoxLayout
#define _Included_org_swdc_qt_internal_layout_SHBoxLayout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_layout_SHBoxLayout
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_layout_SHBoxLayout_create
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
