/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_layout_SBoxLayout */

#ifndef _Included_org_swdc_qt_internal_layout_SBoxLayout
#define _Included_org_swdc_qt_internal_layout_SBoxLayout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    doSetDirection
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_doSetDirection
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    doGetDirection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_doGetDirection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    addSpacing
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_addSpacing
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    addStretch
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_addStretch
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    addSpacerItem
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_addSpacerItem
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    addLayout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_addLayout
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    addStrut
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_addStrut
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    insertSpacing
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_insertSpacing
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    insertStretch
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_insertStretch
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    insertSpacerItem
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_insertSpacerItem
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    insertLayout
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_insertLayout
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_layout_SBoxLayout
 * Method:    insertItem
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_layout_SBoxLayout_insertItem
  (JNIEnv *, jobject, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
