/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_internal_widgets_SKeySequence */

#ifndef _Included_org_swdc_qt_internal_widgets_SKeySequence
#define _Included_org_swdc_qt_internal_widgets_SKeySequence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_create__
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_create__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_create__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    matches
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_matches
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    toString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_toString
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    isDetached
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_isDetached
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    fromString
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_fromString
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    mnemonic
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_mnemonic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SKeySequence
 * Method:    keyBindings
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_qt_internal_widgets_SKeySequence_keyBindings
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
