/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_SApplication */

#ifndef _Included_org_swdc_qt_SApplication
#define _Included_org_swdc_qt_SApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_SApplication
 * Method:    create
 * Signature: (I[Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_QtApplication_create
  (JNIEnv *, jobject, jint, jobjectArray, jstring);

/*
 * Class:     org_swdc_qt_SApplication
 * Method:    exec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_QtApplication_exec
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
