/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"

/* Header for class org_swdc_qt_internal_widgets_SRadioButton */

#ifndef _Included_org_swdc_qt_internal_widgets_SRadioButton
#define _Included_org_swdc_qt_internal_widgets_SRadioButton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_SRadioButton
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SRadioButton_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SRadioButton
 * Method:    sizeHint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SRadioButton_sizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SRadioButton
 * Method:    minimumSizeHint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SRadioButton_minimumSizeHint
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
