/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_internal_widgets_SAbstractScrollArea */

#ifndef _Included_org_swdc_qt_internal_widgets_SAbstractScrollArea
#define _Included_org_swdc_qt_internal_widgets_SAbstractScrollArea
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    verticalScrollBarPolicy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_verticalScrollBarPolicy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    setVerticalScrollBarPolicy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_setVerticalScrollBarPolicy
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    verticalScrollBar
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_verticalScrollBar
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    setVerticalScrollBar
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_setVerticalScrollBar
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    horizontalScrollBarPolicy
 * Signature: (J)J
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_horizontalScrollBarPolicy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    setHorizontalScrollBarPolicy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_setHorizontalScrollBarPolicy
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    horizontalScrollBar
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_horizontalScrollBar
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    setHorizontalScrollBar
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_setHorizontalScrollBar
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    cornerWidget
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_cornerWidget
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    setCornerWidget
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_setCornerWidget
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    addScrollBarWidget
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_addScrollBarWidget
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    scrollBarWidgets
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_scrollBarWidgets
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    viewport
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_viewport
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    setViewport
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_setViewport
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    maximumViewportSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_maximumViewportSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    minimumSizeHint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_minimumSizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    sizeHint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_sizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    setupViewport
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_setupViewport
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    sizeAdjustPolicy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_sizeAdjustPolicy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SAbstractScrollArea
 * Method:    setSizeAdjustPolicy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SAbstractScrollArea_setSizeAdjustPolicy
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
