/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"

/* Header for class org_swdc_qt_internal_widgets_STextEdit */

#ifndef _Included_org_swdc_qt_internal_widgets_STextEdit
#define _Included_org_swdc_qt_internal_widgets_STextEdit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    dispose
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setDocument
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setDocument
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    document
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_document
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setPlaceholderText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setPlaceholderText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    placeholderText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_placeholderText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setTextCursor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setTextCursor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    textCursor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_textCursor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    isReadOnly
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_isReadOnly
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setReadOnly
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setReadOnly
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setTextInteractionFlags
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setTextInteractionFlags
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    fontPointSize
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_fontPointSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    fontFamily
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_fontFamily
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    fontWeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_fontWeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    fontUnderline
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_fontUnderline
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    fontItalic
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_fontItalic
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    textColor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_textColor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    textBackgroundColor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_textBackgroundColor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    currentFont
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_currentFont
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    alignment
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_alignment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    mergeCurrentCharFormat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_mergeCurrentCharFormat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setCurrentCharFormat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setCurrentCharFormat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    currentCharFormat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_currentCharFormat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    autoFormatting
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_autoFormatting
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setAutoFormatting
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setAutoFormatting
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    tabChangesFocus
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_tabChangesFocus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setTabChangesFocus
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setTabChangesFocus
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setDocumentTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setDocumentTitle
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    documentTitle
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_documentTitle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    isUndoRedoEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_isUndoRedoEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setUndoRedoEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setUndoRedoEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    lineWrapMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_lineWrapMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setLineWrapMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setLineWrapMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    lineWrapColumnOrWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_lineWrapColumnOrWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setLineWrapColumnOrWidth
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setLineWrapColumnOrWidth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    wordWrapMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_wordWrapMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setWordWrapMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setWordWrapMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    find
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_find
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    findRegexp
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_findRegexp
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    findRegularExpression
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_findRegularExpression
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    toPlainText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_toPlainText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    toHtml
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_toHtml
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    toMarkdown
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_toMarkdown
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    ensureCursorVisible
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_ensureCursorVisible
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    loadResource
 * Signature: (JILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_loadResource
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    createStandardContextMenu
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_createStandardContextMenu__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    createStandardContextMenu
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_createStandardContextMenu__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    cursorForPosition
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_cursorForPosition
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    cursorRect
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_cursorRect__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    cursorRect
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_cursorRect__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    anchorAt
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_anchorAt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    overwriteMode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_overwriteMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setOverwriteMode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setOverwriteMode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    tabStopDistance
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_tabStopDistance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setTabStopDistance
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setTabStopDistance
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    cursorWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_cursorWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setCursorWidth
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setCursorWidth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    acceptRichText
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_acceptRichText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setAcceptRichText
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setAcceptRichText
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setExtraSelections
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setExtraSelections
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    extraSelections
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_extraSelections
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    moveCursor
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_moveCursor
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    canPaste
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_canPaste
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    inputMethodQuery
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_inputMethodQuery__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    inputMethodQuery
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_inputMethodQuery__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setFontPointSize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setFontPointSize
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setFontFamily
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setFontFamily
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setFontWeight
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setFontWeight
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setFontUnderline
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setFontUnderline
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setFontItalic
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setFontItalic
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setTextColor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setTextColor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setTextBackgroundColor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setTextBackgroundColor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setCurrentFont
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setCurrentFont
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setAlignment
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setAlignment
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setPlainText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setPlainText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setHtml
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setHtml
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setMarkdown
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setMarkdown
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    setText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_setText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    cut
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_cut
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    copy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_copy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    paste
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_paste
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    undo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_undo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    redo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_redo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    selectAll
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_selectAll
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    insertPlainText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_insertPlainText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    insertHtml
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_insertHtml
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    append
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_append
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    scrollToAnchor
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_scrollToAnchor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    zoomIn
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_zoomIn
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextEdit
 * Method:    zoomOut
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextEdit_zoomOut
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
