/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_internal_widgets_SComboBox */

#ifndef _Included_org_swdc_qt_internal_widgets_SComboBox
#define _Included_org_swdc_qt_internal_widgets_SComboBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    maxVisibleItems
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_maxVisibleItems
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setMaxVisibleItems
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setMaxVisibleItems
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setMaxCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setMaxCount
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    maxCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_maxCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    duplicatesEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_duplicatesEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setDuplicatesEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setDuplicatesEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setFrame
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setFrame
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    hasFrame
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_hasFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    findText
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_findText
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    insertPolicy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_insertPolicy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setInsertPolicy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setInsertPolicy
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    sizeAdjustPolicy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_sizeAdjustPolicy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setSizeAdjustPolicy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setSizeAdjustPolicy
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    minimumContentsLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_minimumContentsLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setMinimumContentsLength
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setMinimumContentsLength
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    iconSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_iconSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setIconSize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setIconSize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setPlaceholderText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setPlaceholderText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    placeholderText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_placeholderText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    isEditable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_isEditable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setEditable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setEditable
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setLineEdit
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setLineEdit
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    lineEdit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_lineEdit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    model
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_model
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setModel
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setModel
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    rootModelIndex
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_rootModelIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setRootModelIndex
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setRootModelIndex
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    modelColumn
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_modelColumn
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setModelColumn
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setModelColumn
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    currentIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_currentIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    currentText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_currentText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    currentData
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_currentData
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    itemText
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_itemText
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    itemIcon
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_itemIcon
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    itemData
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_itemData
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    addItem
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_addItem__JLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    addItem
 * Signature: (JJLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_addItem__JJLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    addItems
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_addItems
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    insertItem
 * Signature: (JILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_insertItem__JILjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jint, jstring, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    insertItem
 * Signature: (JIJLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_insertItem__JIJLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jint, jlong, jstring, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    insertItems
 * Signature: (JI[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_insertItems
  (JNIEnv *, jobject, jlong, jint, jobjectArray);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    insertSeparator
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_insertSeparator
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    removeItem
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_removeItem
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setItemText
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setItemText
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setItemIcon
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setItemIcon
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    setItemData
 * Signature: (JIJI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_setItemData
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    sizeHint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_sizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    minimumSizeHint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_minimumSizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    showPopup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_showPopup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SComboBox
 * Method:    hidePopup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SComboBox_hidePopup
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
