/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_internal_widgets_SToolBox */

#ifndef _Included_org_swdc_qt_internal_widgets_SToolBox
#define _Included_org_swdc_qt_internal_widgets_SToolBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    addItem
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_addItem__JJLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    addItem
 * Signature: (JJJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_addItem__JJJLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    insertItem
 * Signature: (JIJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_insertItem__JIJLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jint, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    insertItem
 * Signature: (JIJJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_insertItem__JIJJLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    removeItem
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_removeItem
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    setItemEnabled
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_setItemEnabled
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    isItemEnabled
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_isItemEnabled
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    setItemText
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_setItemText
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    itemText
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_itemText
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    setItemIcon
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_setItemIcon
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    itemIcon
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_itemIcon
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    setItemToolTip
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_setItemToolTip
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    itemToolTip
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_itemToolTip
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    currentIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_currentIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    currentWidget
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_currentWidget
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    widget
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_widget
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    indexOf
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_indexOf
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SToolBox
 * Method:    count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SToolBox_count
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
