/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_internal_widgets_SItemModel */

#ifndef _Included_org_swdc_qt_internal_widgets_SItemModel
#define _Included_org_swdc_qt_internal_widgets_SItemModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_SItemModel
 * Method:    create
 * Signature: (Lorg/swdc/qt/widgets/ItemModel;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SItemModel_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_swdc_qt_internal_widgets_SItemModel
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SItemModel_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SItemModel
 * Method:    resetReferences
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SItemModel_resetReferences
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
