/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_internal_widgets_STextBrowser */

#ifndef _Included_org_swdc_qt_internal_widgets_STextBrowser
#define _Included_org_swdc_qt_internal_widgets_STextBrowser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    source
 * Signature: (J)J
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_source
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    sourceType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_sourceType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    searchPaths
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_searchPaths
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    setSearchPaths
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_setSearchPaths
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    loadResource
 * Signature: (JILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_loadResource
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    isBackwardAvailable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_isBackwardAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    isForwardAvailable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_isForwardAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    clearHistory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_clearHistory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    historyTitle
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_historyTitle
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    historyUrl
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_historyUrl
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    backwardHistoryCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_backwardHistoryCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    forwardHistoryCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_forwardHistoryCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    openExternalLinks
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_openExternalLinks
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    setOpenExternalLinks
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_setOpenExternalLinks
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    openLinks
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_openLinks
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    setOpenLinks
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_setOpenLinks
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    setSource
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_setSource
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    backward
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_backward
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    forward
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_forward
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    home
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_home
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STextBrowser
 * Method:    reload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STextBrowser_reload
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
