/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include <qtableview.h>
/* Header for class org_swdc_qt_internal_widgets_STabWidget */

#ifndef _Included_org_swdc_qt_internal_widgets_STabWidget
#define _Included_org_swdc_qt_internal_widgets_STabWidget
#ifdef __cplusplus
extern "C" {
#endif



/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_create
  (JNIEnv *, jobject);


/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    addTab
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_addTab
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    insertTab
 * Signature: (JIJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_insertTab
  (JNIEnv *, jobject, jlong, jint, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    removeTab
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_removeTab
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    isTabEnabled
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_isTabEnabled
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setTabEnabled
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setTabEnabled
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    isTabVisible
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_isTabVisible
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setTabVisible
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setTabVisible
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    tabText
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_tabText
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setTabText
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setTabText
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setTabToolTip
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setTabToolTip
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    tabToolTip
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_tabToolTip
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setTabWhatsThis
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setTabWhatsThis
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    tabWhatsThis
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_tabWhatsThis
  (JNIEnv *, jobject, jlong,jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    currentIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_currentIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    tabPosition
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_tabPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setTabPosition
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setTabPosition
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    tabsClosable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_tabsClosable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setTabsClosable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setTabsClosable
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    isMovable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_isMovable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setMovable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setMovable
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    tabShape
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_tabShape
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setTabShape
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setTabShape
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    usesScrollButtons
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_usesScrollButtons
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setUsesScrollButtons
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setUsesScrollButtons
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    documentMode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_documentMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setDocumentMode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setDocumentMode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    tabBarAutoHide
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_tabBarAutoHide
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    setTabBarAutoHide
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_setTabBarAutoHide
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    sizeHint
 * Signature: (J)Lorg/swdc/qt/beans/SSize;
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_sizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    minimumSizeHint
 * Signature: (J)Lorg/swdc/qt/beans/SSize;
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_minimumSizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    heightForWidth
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_heightForWidth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_STabWidget
 * Method:    hasHeightForWidth
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_STabWidget_hasHeightForWidth
  (JNIEnv *, jobject, jlong);


#ifdef __cplusplus
}
#endif
#endif
