/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_internal_widgets_SDoubleSpinBox */

#ifndef _Included_org_swdc_qt_internal_widgets_SDoubleSpinBox
#define _Included_org_swdc_qt_internal_widgets_SDoubleSpinBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    value
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_value
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    prefix
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_prefix
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    setPrefix
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_setPrefix
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    suffix
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_suffix
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    setSuffix
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_setSuffix
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    cleanText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_cleanText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    singleStep
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_singleStep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    setSingleStep
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_setSingleStep
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    minimum
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_minimum
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    setMinimum
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_setMinimum
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    maximum
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_maximum
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    setMaximum
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_setMaximum
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    setRange
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_setRange
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    stepType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_stepType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    setStepType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_setStepType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    decimals
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_decimals
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    setDecimals
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_setDecimals
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    valueFromText
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_valueFromText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    textFromValue
 * Signature: (JD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_textFromValue
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_widgets_SDoubleSpinBox
 * Method:    fixup
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDoubleSpinBox_fixup
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
