/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_internal_widgets_SDateTimeEdit */

#ifndef _Included_org_swdc_qt_internal_widgets_SDateTimeEdit
#define _Included_org_swdc_qt_internal_widgets_SDateTimeEdit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_create
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    dateTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_dateTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    date
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_date
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    time
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_time
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    calendar
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_calendar
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setCalendar
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setCalendar
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    minimumDateTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_minimumDateTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    clearMinimumDateTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_clearMinimumDateTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setMinimumDateTime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setMinimumDateTime
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    maximumDateTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_maximumDateTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    clearMaximumDateTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_clearMaximumDateTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setMaximumDateTime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setMaximumDateTime
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setDateTimeRange
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setDateTimeRange
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    minimumDate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_minimumDate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setMinimumDate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setMinimumDate
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    clearMinimumDate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_clearMinimumDate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    maximumDate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_maximumDate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setMaximumDate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setMaximumDate
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    clearMaximumDate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_clearMaximumDate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setDateRange
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setDateRange
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    minimumTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_minimumTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setMinimumTime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setMinimumTime
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    clearMinimumTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_clearMinimumTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    maximumTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_maximumTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setMaximumTime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setMaximumTime
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    clearMaximumTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_clearMaximumTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setTimeRange
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setTimeRange
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    currentSection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_currentSection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    sectionAt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_sectionAt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setCurrentSection
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setCurrentSection
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    currentSectionIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_currentSectionIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setCurrentSectionIndex
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setCurrentSectionIndex
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    sectionCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_sectionCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setSelectedSection
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setSelectedSection
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    sectionText
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_sectionText
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    displayFormat
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_displayFormat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setDisplayFormat
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setDisplayFormat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    calendarPopup
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_calendarPopup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setCalendarPopup
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setCalendarPopup
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    timeSpec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_timeSpec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    setTimeSpec
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_setTimeSpec
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    sizeHint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_sizeHint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_widgets_SDateTimeEdit
 * Method:    stepBy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_widgets_SDateTimeEdit_stepBy
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
