/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_qt_Platform */

#ifndef _Included_org_swdc_qt_Platform
#define _Included_org_swdc_qt_Platform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_Platform
 * Method:    runLater
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_Platform_runLater
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
