/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextBlockIterator */

#ifndef _Included_org_swdc_qt_internal_text_STextBlockIterator
#define _Included_org_swdc_qt_internal_text_STextBlockIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextBlockIterator
 * Method:    hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextBlockIterator_hasNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockIterator
 * Method:    next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextBlockIterator_next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockIterator
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockIterator_dispose
  (JNIEnv *, jobject, jlong);
#ifdef __cplusplus
}
#endif
#endif
