/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextBlockFormat */

#ifndef _Included_org_swdc_qt_internal_text_STextBlockFormat
#define _Included_org_swdc_qt_internal_text_STextBlockFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_isValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setAlignment
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setAlignment
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    alignment
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_alignment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setTopMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setTopMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    topMargin
 * Signature: (J)J
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_topMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setBottomMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setBottomMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    bottomMargin
 * Signature: (J)J
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_bottomMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setLeftMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setLeftMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    leftMargin
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_leftMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setRightMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setRightMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    rightMargin
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_rightMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setTextIndent
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setTextIndent
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    textIndent
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_textIndent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setIndent
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setIndent
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    indent
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_indent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setHeadingLevel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setHeadingLevel
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    headingLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_headingLevel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setLineHeight
 * Signature: (JDI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setLineHeight
  (JNIEnv *, jobject, jlong, jdouble, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    lineHeight
 * Signature: (JDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_lineHeight__JDD
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    lineHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_lineHeight__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    lineHeightType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_lineHeightType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setNonBreakableLines
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setNonBreakableLines
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    nonBreakableLines
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_nonBreakableLines
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setPageBreakPolicy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setPageBreakPolicy
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    setMarker
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_setMarker
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextBlockFormat
 * Method:    marker
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextBlockFormat_marker
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
