/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextFrameIterator */

#ifndef _Included_org_swdc_qt_internal_text_STextFrameIterator
#define _Included_org_swdc_qt_internal_text_STextFrameIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextFrameIterator
 * Method:    hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextFrameIterator_hasNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameIterator
 * Method:    next
 * Signature: (J)Lorg/swdc/qt/internal/text/STextFrameIterItem;
 */
JNIEXPORT jobject JNICALL Java_org_swdc_qt_internal_text_STextFrameIterator_next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameIterator
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameIterator_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
