/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextDocument */

#ifndef _Included_org_swdc_qt_internal_text_STextDocument
#define _Included_org_swdc_qt_internal_text_STextDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    isEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextDocument_isEmpty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setUndoRedoEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setUndoRedoEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    isUndoRedoEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextDocument_isUndoRedoEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    isUndoAvailable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextDocument_isUndoAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    isRedoAvailable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextDocument_isRedoAvailable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    availableUndoSteps
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextDocument_availableUndoSteps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    availableRedoSteps
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextDocument_availableRedoSteps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    revision
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextDocument_revision
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setDocumentLayout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setDocumentLayout
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    documentLayout
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_documentLayout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setMetaInformation
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setMetaInformation
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    metaInformation
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_text_STextDocument_metaInformation
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    toHtml
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_text_STextDocument_toHtml
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setHtml
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setHtml
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    toMarkdown
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_text_STextDocument_toMarkdown
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setMarkdown
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setMarkdown
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    toRawText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_text_STextDocument_toRawText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    toPlainText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_text_STextDocument_toPlainText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setPlainText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setPlainText
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    characterAt
 * Signature: (JI)C
 */
JNIEXPORT jchar JNICALL Java_org_swdc_qt_internal_text_STextDocument_characterAt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    find
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_find__JLjava_lang_String_2II
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    find
 * Signature: (JLjava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_find__JLjava_lang_String_2JI
  (JNIEnv *, jobject, jlong, jstring, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    findRegExp
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_findRegExp__JJII
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    findRegExp
 * Signature: (JJJI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_findRegExp__JJJI
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    findRegularExpression
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_findRegularExpression__JJII
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    findRegularExpression
 * Signature: (JJJI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_findRegularExpression__JJJI
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    frameAt
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_frameAt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    rootFrame
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_rootFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    object
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_object
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    objectForFormat
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_objectForFormat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    findBlock
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_findBlock
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    findBlockByNumber
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_findBlockByNumber
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    findBlockByLineNumber
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_findBlockByLineNumber
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    begin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_begin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    end
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_end
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    firstBlock
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_firstBlock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    lastBlock
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_lastBlock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setPageSize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setPageSize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    pageSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_pageSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setDefaultFont
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setDefaultFont
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    defaultFont
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_defaultFont
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    pageCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextDocument_pageCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    isModified
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextDocument_isModified
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    resource
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_resource
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    addResource
 * Signature: (ILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_addResource
  (JNIEnv *, jobject, jlong, jint, jstring, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    allFormats
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_qt_internal_text_STextDocument_allFormats
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    markContentsDirty
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_markContentsDirty
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setUseDesignMetrics
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setUseDesignMetrics
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    useDesignMetrics
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextDocument_useDesignMetrics
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    drawContents
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_drawContents
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setTextWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setTextWidth
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    textWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextDocument_textWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    idealWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextDocument_idealWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    indentWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextDocument_indentWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setIndentWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setIndentWidth
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    documentMargin
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextDocument_documentMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    setDocumentMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_setDocumentMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    adjustSize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocument_adjustSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocument_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    blockCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextDocument_blockCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    lineCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextDocument_lineCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocument
 * Method:    characterCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextDocument_characterCount
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
