/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextTableFormat */

#ifndef _Included_org_swdc_qt_internal_text_STextTableFormat
#define _Included_org_swdc_qt_internal_text_STextTableFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    columns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_columns
  (JNIEnv *, jobject,jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    setColumnWidthConstraints
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_setColumnWidthConstraints
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    columnWidthConstraints
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_columnWidthConstraints
  (JNIEnv *, jobject,jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    clearColumnWidthConstraints
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_clearColumnWidthConstraints
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    cellSpacing
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_cellSpacing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    setCellSpacing
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_setCellSpacing
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    cellPadding
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_cellPadding
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    setCellPadding
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_setCellPadding
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    setAlignment
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_setAlignment
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    alignment
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_alignment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    setHeaderRowCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_setHeaderRowCount
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    headerRowCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_headerRowCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    setBorderCollapse
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_setBorderCollapse
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_text_STextTableFormat
 * Method:    borderCollapse
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextTableFormat_borderCollapse
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
