/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextFragment */

#ifndef _Included_org_swdc_qt_internal_text_STextFragment
#define _Included_org_swdc_qt_internal_text_STextFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextFragment
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextFragment_create__
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_text_STextFragment
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextFragment_create__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFragment
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFragment_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFragment
 * Method:    position
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextFragment_position
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFragment
 * Method:    length
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextFragment_length
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFragment
 * Method:    contains
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_STextFragment_contains
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextFragment
 * Method:    charFormat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextFragment_charFormat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFragment
 * Method:    charFormatIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextFragment_charFormatIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFragment
 * Method:    text
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_text_STextFragment_text
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
