/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextLength */

#ifndef _Included_org_swdc_qt_internal_text_STextLength
#define _Included_org_swdc_qt_internal_text_STextLength
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextLength
 * Method:    create
 * Signature: (ID)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextLength_create
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextLength
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextLength_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextLength
 * Method:    type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextLength_type
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextLength
 * Method:    value
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextLength_value
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextLength
 * Method:    rawValue
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextLength_rawValue
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
