/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextOptionTab */

#ifndef _Included_org_swdc_qt_internal_text_STextOptionTab
#define _Included_org_swdc_qt_internal_text_STextOptionTab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextOptionTab
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextOptionTab_create__
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_text_STextOptionTab
 * Method:    create
 * Signature: (DIC)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextOptionTab_create__DIC
  (JNIEnv *, jobject, jdouble, jint, jchar);

/*
 * Class:     org_swdc_qt_internal_text_STextOptionTab
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextOptionTab_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextOptionTab
 * Method:    position
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextOptionTab_position__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextOptionTab
 * Method:    position
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextOptionTab_position__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextOptionTab
 * Method:    type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextOptionTab_type__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextOptionTab
 * Method:    type
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextOptionTab_type__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextOptionTab
 * Method:    delimiter
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_org_swdc_qt_internal_text_STextOptionTab_delimiter__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextOptionTab
 * Method:    delimiter
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextOptionTab_delimiter__JC
  (JNIEnv *, jobject, jlong, jchar);

#ifdef __cplusplus
}
#endif
#endif
