/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_SAbstractTextLayout */

#ifndef _Included_org_swdc_qt_internal_text_SAbstractTextLayout
#define _Included_org_swdc_qt_internal_text_SAbstractTextLayout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    draw
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_draw
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    anchorAt
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_anchorAt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    imageAt
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_imageAt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    formatAt
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_formatAt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    blockWithMarkerAt
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_blockWithMarkerAt
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    pageCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_pageCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    documentSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_documentSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    frameBoundingRect
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_frameBoundingRect
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    blockBoundingRect
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_blockBoundingRect
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    document
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_document
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    registerHandler
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_registerHandler
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SAbstractTextLayout
 * Method:    unregisterHandler
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_SAbstractTextLayout_unregisterHandler
  (JNIEnv *, jobject, jlong, jint, jlong);


#ifdef __cplusplus
}
#endif
#endif
