/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_SRegularExpressionMatchIterator */

#ifndef _Included_org_swdc_qt_internal_text_SRegularExpressionMatchIterator
#define _Included_org_swdc_qt_internal_text_SRegularExpressionMatchIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_SRegularExpressionMatchIterator
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_SRegularExpressionMatchIterator_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SRegularExpressionMatchIterator
 * Method:    hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_text_SRegularExpressionMatchIterator_hasNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SRegularExpressionMatchIterator
 * Method:    nextMatch
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_SRegularExpressionMatchIterator_nextMatch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SRegularExpressionMatchIterator
 * Method:    peekNextMatch
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_SRegularExpressionMatchIterator_peekNextMatch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SRegularExpressionMatchIterator
 * Method:    regularExpression
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_SRegularExpressionMatchIterator_regularExpression
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_SRegularExpressionMatchIterator
 * Method:    matchType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_SRegularExpressionMatchIterator_matchType
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
