/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextDocumentLayoutPaintContext */

#ifndef _Included_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
#define _Included_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    cursorPosition
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_cursorPosition__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    cursorPosition
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_cursorPosition__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    palette
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_palette__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    palette
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_palette__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    clip
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_clip__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    clip
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_clip__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    selections
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_selections__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextDocumentLayoutPaintContext
 * Method:    selections
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextDocumentLayoutPaintContext_selections__J_3J
  (JNIEnv *, jobject, jlong, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
