/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_text_STextFrameFormat */

#ifndef _Included_org_swdc_qt_internal_text_STextFrameFormat
#define _Included_org_swdc_qt_internal_text_STextFrameFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setPosition
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setPosition
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    position
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_position
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setBorder
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setBorder
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    border
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_border
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setBorderBrush
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setBorderBrush
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    borderBrush
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_borderBrush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setBorderStyle
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setBorderStyle
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    borderStyle
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_borderStyle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    margin
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_margin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setTopMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setTopMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    topMargin
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_topMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setBottomMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setBottomMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    bottomMargin
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_bottomMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setLeftMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setLeftMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    leftMargin
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_leftMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setRightMargin
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setRightMargin
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    rightMargin
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_rightMargin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setPadding
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setPadding
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    padding
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_padding
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setWidth__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setWidth
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setWidth__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    width
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_width
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setHeight
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setHeight__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setHeight
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setHeight__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    height
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_height
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_text_STextFrameFormat
 * Method:    setPageBreakPolicy
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_text_STextFrameFormat_setPageBreakPolicy
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
