/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_date_SDate */

#ifndef _Included_org_swdc_qt_internal_date_SDate
#define _Included_org_swdc_qt_internal_date_SDate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SDate_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_date_SDate_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    year
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_year__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    month
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_month__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    day
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_day__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    dayOfWeek
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_dayOfWeek__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    dayOfYear
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_dayOfYear__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    daysInMonth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_daysInMonth__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    daysInYear
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_daysInYear__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    weekNumber
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_weekNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    year
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_year__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    month
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_month__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    day
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_day__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    dayOfWeek
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_dayOfWeek__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    dayOfYear
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_dayOfYear__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    daysInMonth
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_daysInMonth__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    daysInYear
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SDate_daysInYear__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    setDate
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SDate_setDate__JIII
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    setDate
 * Signature: (JIIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SDate_setDate__JIIIJ
  (JNIEnv *, jobject, jlong, jint, jint, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    addDays
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SDate_addDays
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    addMonths
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SDate_addMonths__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    addYears
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SDate_addYears__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    addMonths
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SDate_addMonths__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    addYears
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SDate_addYears__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    daysTo
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SDate_daysTo
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SDate_equals
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    isBefore
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SDate_isBefore
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SDate
 * Method:    isAfter
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SDate_isAfter
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
