/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_date_SCalendar */

#ifndef _Included_org_swdc_qt_internal_date_SCalendar
#define _Included_org_swdc_qt_internal_date_SCalendar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SCalendar_create__
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SCalendar_create__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_date_SCalendar_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SCalendar_isValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    daysInMonth
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SCalendar_daysInMonth
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    daysInYear
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SCalendar_daysInYear
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    monthsInYear
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SCalendar_monthsInYear
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    isDateValid
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SCalendar_isDateValid
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    isLeapYear
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SCalendar_isLeapYear
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    isGregorian
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SCalendar_isGregorian
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    isLunar
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SCalendar_isLunar
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    isLuniSolar
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SCalendar_isLuniSolar
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    isSolar
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SCalendar_isSolar
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    isProleptic
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SCalendar_isProleptic
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    hasYearZero
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_date_SCalendar_hasYearZero
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    maximumDaysInMonth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SCalendar_maximumDaysInMonth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    minimumDaysInMonth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SCalendar_minimumDaysInMonth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    maximumMonthsInYear
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SCalendar_maximumMonthsInYear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_date_SCalendar_name
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    dateFromParts
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_date_SCalendar_dateFromParts
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    dayOfWeek
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_date_SCalendar_dayOfWeek
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_date_SCalendar
 * Method:    availableCalendars
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_swdc_qt_internal_date_SCalendar_availableCalendars
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
