/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_graphics_SRadialGradient */

#ifndef _Included_org_swdc_qt_internal_graphics_SRadialGradient
#define _Included_org_swdc_qt_internal_graphics_SRadialGradient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_create__
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    create
 * Signature: (DDDDD)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_create__DDDDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    center
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_center
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    setCenter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_setCenter__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    setCenter
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_setCenter__JDD
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    focalPoint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_focalPoint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    setFocalPoint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_setFocalPoint__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    setFocalPoint
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_setFocalPoint__JDD
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    radius
 * Signature: (J)V
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_radius
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    setRadius
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_setRadius
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    centerRadius
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_centerRadius
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    setCenterRadius
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_setCenterRadius
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    focalRadius
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_focalRadius
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    setFocalRadius
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_setFocalRadius
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SRadialGradient
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SRadialGradient_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
