/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_graphics_SPainterPath */

#ifndef _Included_org_swdc_qt_internal_graphics_SPainterPath
#define _Included_org_swdc_qt_internal_graphics_SPainterPath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    swap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_swap
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    reserve
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_reserve
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    capacity
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_capacity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    closeSubpath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_closeSubpath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    moveTo
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_moveTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    lineTo
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_lineTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    arcMoveTo
 * Signature: (JDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_arcMoveTo
  (JNIEnv * env, jobject self, jlong pointer, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    arcTo
 * Signature: (JDDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_arcTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    cubicTo
 * Signature: (JDDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_cubicTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    quadTo
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_quadTo
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    addRect
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_addRect
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    addEllipse
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_addEllipse
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    addPath
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_addPath
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    addRoundedRect
 * Signature: (JDDDDDDI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_addRoundedRect
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    connectPath
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_connectPath
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    translate
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_translate
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    isEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_isEmpty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    fillRule
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_fillRule
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    setFillRule
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_setFillRule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    length
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_length
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    percentAtLength
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_percentAtLength
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    angleAtPercent
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_angleAtPercent
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    slopeAtPercent
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_slopeAtPercent
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    intersects
 * Signature: (JJ)Z
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_intersects
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    contains
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_contains
  (JNIEnv *, jobject, jlong, jlong);


/*
 * Class:     org_swdc_qt_internal_graphics_SPainterPath
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPainterPath_dispose
  (JNIEnv *, jobject, jlong);
#ifdef __cplusplus
}
#endif
#endif
