/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_graphics_STransformation */

#ifndef _Included_org_swdc_qt_internal_graphics_STransformation
#define _Included_org_swdc_qt_internal_graphics_STransformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_STransformation_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    isAffine
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_STransformation_isAffine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    isIdentity
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_STransformation_isIdentity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    isInvertible
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_STransformation_isInvertible
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    isScaling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_STransformation_isScaling
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    isRotating
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_STransformation_isRotating
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    isTranslating
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_STransformation_isTranslating
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_STransformation_type
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    determinant
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_determinant
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    m11
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_m11
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    m12
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_m12
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    m13
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_m13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    m21
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_m21
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    m22
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_m22
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    m23
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_m23
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    m31
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_m31
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    m32
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_m32
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    m33
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_m33
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    dx
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_dx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    dy
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_STransformation_dy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    setMatrix
 * Signature: (JDDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_STransformation_setMatrix
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    translate
 * Signature: (JDD)J
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_STransformation_translate
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    scale
 * Signature: (JDD)J
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_STransformation_scale
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    shear
 * Signature: (JDD)J
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_STransformation_shear
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    rotate
 * Signature: (JDI)J
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_STransformation_rotate
  (JNIEnv *, jobject, jlong, jdouble, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    rotateRadians
 * Signature: (JDI)J
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_STransformation_rotateRadians
  (JNIEnv *, jobject, jlong, jdouble, jint);


/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_STransformation_dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    fromTranslate
 * Signature: (DD)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_STransformation_fromTranslate
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_STransformation
 * Method:    fromScale
 * Signature: (DD)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_STransformation_fromScale
  (JNIEnv *, jclass, jdouble, jdouble);



#ifdef __cplusplus
}
#endif
#endif
