/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_graphics_SIcon */

#ifndef _Included_org_swdc_qt_internal_graphics_SIcon
#define _Included_org_swdc_qt_internal_graphics_SIcon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SIcon_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    createWithFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SIcon_createWithFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    createWithPixmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SIcon_createWithPixmap
  (JNIEnv *, jobject, jlong);


/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    actualSize
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SIcon_actualSize
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_graphics_SIcon_name
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    paint
 * Signature: (JJJJII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SIcon_paint__JJJJII
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    paint
 * Signature: (JJIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SIcon_paint__JJIIIIIII
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    addPixmap
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SIcon_addPixmap
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    addFile
 * Signature: (JLjava/lang/String;JII)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SIcon_addFile
  (JNIEnv *, jobject, jlong, jstring, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    setIsMask
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SIcon_setIsMask
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    isMask
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SIcon_isMask
  (JNIEnv *, jobject, jlong);


/*
 * Class:     org_swdc_qt_internal_graphics_SIcon
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SIcon_dispose
  (JNIEnv *, jobject, jlong);
#ifdef __cplusplus
}
#endif
#endif
