/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_graphics_SPixmap */

#ifndef _Included_org_swdc_qt_internal_graphics_SPixmap
#define _Included_org_swdc_qt_internal_graphics_SPixmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    create
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_create__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_create__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_width
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_height
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    size
 * Signature: (J)Lorg/swdc/qt/beans/SSize;
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    rect
 * Signature: (J)Lorg/swdc/qt/beans/SRect;
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_rect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    depth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_depth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    fill
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_fill
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    devicePixelRatio
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_devicePixelRatio
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    setDevicePixelRatio
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_setDevicePixelRatio
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    hasAlpha
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_hasAlpha
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    hasAlphaChannel
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_hasAlphaChannel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    scaled
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_scaled
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    scaledToWidth
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_scaledToWidth
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    scaledToHeight
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_scaledToHeight
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    transformed
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_transformed
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    toImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_toImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    load
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_load
  (JNIEnv *, jobject, jlong, jstring, jstring, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    loadFromData
 * Signature: (J[BLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_loadFromData
  (JNIEnv *, jobject, jlong, jbyteArray, jstring, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    save
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_save
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    convertFromImage
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_convertFromImage
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    copy
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_copy
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    isQBitmap
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_isQBitmap
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    mask
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_mask
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    setMask
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_setMask
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    createHeuristicMask
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_createHeuristicMask
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    createMaskFromColor
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_createMaskFromColor
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    grabWidget
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_grabWidget
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    fromImage
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_fromImage
  (JNIEnv *, jclass, jlong, jlong);


/*
 * Class:     org_swdc_qt_internal_graphics_SPixmap
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SPixmap_dispose
  (JNIEnv *, jobject, jlong);


#ifdef __cplusplus
}
#endif
#endif
