/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_graphics_SBrush */

#ifndef _Included_org_swdc_qt_internal_graphics_SBrush
#define _Included_org_swdc_qt_internal_graphics_SBrush
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SBrush_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    style
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SBrush_style
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    setStyle
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SBrush_setStyle
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    transform
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SBrush_transform
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    setTransform
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SBrush_setTransform
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    texture
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SBrush_texture
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    setTexture
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SBrush_setTexture
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    textureImage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SBrush_textureImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    setTextureImage
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SBrush_setTextureImage
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    color
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SBrush_color
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    setColor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SBrush_setColor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    isOpaque
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_qt_internal_graphics_SBrush_isOpaque
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SBrush
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SBrush_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
