/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_graphics_SGradient */

#ifndef _Included_org_swdc_qt_internal_graphics_SGradient
#define _Included_org_swdc_qt_internal_graphics_SGradient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SGradient_create
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SGradient_type
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    setSpread
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SGradient_setSpread
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    spread
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SGradient_spread
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    setColorAt
 * Signature: (JDJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SGradient_setColorAt
  (JNIEnv *, jobject, jlong, jdouble, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    setStops
 * Signature: (J[Lorg/apache/commons/lang3/tuple/Pair;)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SGradient_setStops
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    stops
 * Signature: (J)[Lorg/apache/commons/lang3/tuple/Pair;
 */
JNIEXPORT jobjectArray JNICALL Java_org_swdc_qt_internal_graphics_SGradient_stops
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    coordinateMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SGradient_coordinateMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    setCoordinateMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SGradient_setCoordinateMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    interpolationMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SGradient_interpolationMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    setInterpolationMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SGradient_setInterpolationMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_swdc_qt_internal_graphics_SGradient
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SGradient_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
