/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_graphics_SConicalGradient */

#ifndef _Included_org_swdc_qt_internal_graphics_SConicalGradient
#define _Included_org_swdc_qt_internal_graphics_SConicalGradient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_graphics_SConicalGradient
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SConicalGradient_create__
  (JNIEnv *, jobject);

/*
 * Class:     org_swdc_qt_internal_graphics_SConicalGradient
 * Method:    create
 * Signature: (DDD)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SConicalGradient_create__DDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SConicalGradient
 * Method:    center
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SConicalGradient_center
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SConicalGradient
 * Method:    setCenter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SConicalGradient_setCenter__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SConicalGradient
 * Method:    setCenter
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SConicalGradient_setCenter__JDD
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SConicalGradient
 * Method:    angle
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_swdc_qt_internal_graphics_SConicalGradient_angle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SConicalGradient
 * Method:    setAngle
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SConicalGradient_setAngle
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SConicalGradient
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_swdc_qt_internal_graphics_SConicalGradient_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
