/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jni.h"
/* Header for class org_swdc_qt_internal_graphics_SRgb */

#ifndef _Included_org_swdc_qt_internal_graphics_SRgb
#define _Included_org_swdc_qt_internal_graphics_SRgb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_qt_internal_graphics_SRgb
 * Method:    red
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SRgb_red
  (JNIEnv *, jobject,jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRgb
 * Method:    blue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SRgb_blue
  (JNIEnv *, jobject,jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRgb
 * Method:    green
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SRgb_green
  (JNIEnv *, jobject,jlong);


/*
 * Class:     org_swdc_qt_internal_graphics_SRgb
 * Method:    alpha
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_qt_internal_graphics_SRgb_alpha
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRgb
 * Method:    rgbValue
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SRgb_rgbValue
  (JNIEnv *, jobject, jint, jint, jint, jdouble);

/*
 * Class:     org_swdc_qt_internal_graphics_SRgb
 * Method:    rgbValue
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_qt_internal_graphics_SRgb_rgbValue__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_swdc_qt_internal_graphics_SRgb
 * Method:    toHexString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_graphics_SRgb_toHexString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_swdc_qt_internal_graphics_SRgb
 * Method:    toRgbString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_swdc_qt_internal_graphics_SRgb_toRgbString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
